Support failed allocation metrics in 2.2.0
mweinelt/kea-exporter pull request #26
Opened 2022-10-10 01:45 UTC by glendekoning

Fixes #25

2022-10-11 21:58 UTC, mweinelt requested changes

2022-10-11 21:58 UTC, mweinelt commented on kea_exporter/kea.py
> +                f'{self.prefix_dhcp4}_allocation_fail_total',
```suggestion
                f'{self.prefix_dhcp4}_allocations_failed_total',
```

I think that's more in line with other metrics. What do you think?

2022-10-11 21:58 UTC, mweinelt commented on kea_exporter/kea.py
> +                f'{self.prefix_dhcp4}_reservation_conflicts',
This is a unit-less accumulation and should therefore carry the `_total` suffix.

```suggestion
                f'{self.prefix_dhcp4}_reservation_conflicts_total',
```

2022-10-11 21:58 UTC, mweinelt commented on kea_exporter/kea.py
> +                'metric' : 'reservation_conflicts',
This is a unit-less accumulation and should therefore use the `_total` suffix.

```suggestion
                'metric' : 'reservation_conflicts_total',
```

2022-10-11 21:58 UTC, mweinelt commented on kea_exporter/kea.py
> +        ]
So this is a metric that appears on the global and subnet level. I wonder whether it would be best to create separate ignore lists altogether.

2022-10-11 21:58 UTC, mweinelt commented on kea_exporter/kea.py
> +                f'{self.prefix_dhcp6}_allocation_fail_total',
Same as above.

2022-10-11 21:58 UTC, mweinelt commented on kea_exporter/kea.py
> +                f'{self.prefix_dhcp6}_reservation_conflicts',
Same as above.

2022-10-11 21:58 UTC, mweinelt commented on kea_exporter/kea.py
> +        ]
Same as above.

2022-10-12 20:44 UTC, glendekoning commented on kea_exporter/kea.py
> +        ]
Yes it does i was trying to find the easiest way to resolve this. I think you are right it will be simpler to just have 2 lists one for global and subsets. i will give it a go tonight

2022-10-12 22:08 UTC, mweinelt commented on kea_exporter/kea.py
> +        self.statsdata = self.query('statistic-get-all')
Looks like that's leftover from debugging?

2022-10-12 22:11 UTC, glendekoning commented on kea_exporter/kea.py
> +        self.statsdata = self.query('statistic-get-all')
Yup sure is, should be fixed now

2022-10-12 22:13 UTC, glendekoning commented on kea_exporter/kea.py
> +        ]
Let me know what you think of how i did it. hopefully this is a little cleaner and easier to understand.

2022-10-12 23:04 UTC, mweinelt requested changes

2022-10-13 00:41 UTC, mweinelt commented on kea_exporter/kea.py
> +                    'allocation': 'shared-network'
I'm not sure allocation is the correct word here. When we talk about an allocation it is the process of reserving an address for a client. The label value talks about whether that happened in the context of

- a shared network
- a subnet
- because there were no pools
- because the client didn't match any class

I'm not sure, but I think `context` would be more on point.

2022-10-13 00:41 UTC, mweinelt commented on kea_exporter/kea.py
> +            'declined-addresses',
```suggestion
            # metrics that exist at the subnet level in more detail
            'cumulative-assigned-addresses',
            'declined-addresses',
```

2022-10-13 00:56 UTC, glendekoning commented on kea_exporter/kea.py
> +                    'allocation': 'shared-network'
Yes  that sounds like a more logical label i didn't quite know how to approach that either. lets go with `context`.

2022-10-13 01:12 UTC, mweinelt approved these changes

2022-10-13 01:12 UTC, mweinelt commented
Thanks, that looks pretty good.

2022-10-13 01:12 UTC, merged

2022-10-13 01:13 UTC, glendekoning commented
Awesome thanks for your help !